#!/bin/sh

# Absolute path where the script is located
ABSPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Host computer terminal 
TERMINAL="mate-terminal"

# Directory to checkout git code
GITDIR="/root/git"

# Directory to use for production code
PRODDIR="/opt/guardian_angel"

# Relative directory that contains binary packages
DEBDIR="debs"

# Desired root password
ROOTPWD="zaq1xsw2"

# File lists to install from multiple sources
APTFILE=$ABSPATH/packages.list
PIPFILE=$ABSPATH/pip.list
GITFILE=$ABSPATH/git.list
SSHFILE=$ABSPATH/ssh.list

# Log File location
LOGFILE=$ABSPATH/autoinstall.log
